pub const BLACKLIST: &[&str] = &[
    "unins",
    "uninstall",
    "desinstalar",
    "setup",
    "installer",
    "install",
    "msiexec",
    "vcredist",
    "dotnet-runtime",
    "bootstrapper",
    "clicktorun",
    "dxwebsetup",
    "update",
    "updater",
    "autoupdate",
    "patcher",
    "maint",
    "fix",
    "helper",
    "broker",
    "host",
    "agent",
    "service",
    "background",
    "proxy",
    "watchdog",
    "daemon",
    "bridge",
    "overlay",
    "telemetry",
    "monitor",
    "commandline",
    "headless",
    "launcher_helper",
    "driver",
    "vulkan",
    "physx",
    "notification_helper",
    "crash_handler",
    "crash",
    "diagnostics",
    "troubleshoot",
    "error",
    "crashreporter",
    "crashhandler",
    "dump",
    "report",
    "log",
    "feedback",
    "msinfo",
    "systemsettings",
    "toastnotification",
    "microsoft.windows.",
    "softwarelogo",
    "adminflows",
    "sysinfo",
    "coretools",
    "runtimebroker",
    "sihost",
    "ctfmon",
    "dllhost",
    "rundll",
    "conhost",
    "csrss",
    "svchost",
    "wininit",
    "winlogon",
    "lsass",
    "smss",
    "fontview",
    "atbroker",
    "systemreset",
    "isoburn",
    "magnify",
    "narrator",
    "osk",
    "sysprep",
    "wsreset",
    "taskhost",
    "nacl",
    "swiftshader",
    "widevine",
    "clearkey",
    "srl",
    "squirrel",
    "nuget",
    "chocolatey",
    "elevation_service",
    "readme",
    "license",
    "changelog",
    "credits",
    "copyright",
    "legal",
    "manifest",
    "metadata",
    "config",
    "settings",
];

pub const DIR_BLACKLIST: &[&str] = &[
    "node_modules",
    "target",
    ".git",
    ".svn",
    "dist",
    "build",
    "temp",
    "tmp",
    "cache",
    "logs",
    "appdata\\local\\temp",
    "windows\\winsxs",
    "windows\\servicing",
    "windows\\softwaredistribution",
    "common files",
    "microsoft shared",
    "steamapps\\common",
    ".vs",
    ".idea",
    ".vscode",
    "vendor",
    "obj",
    "bin",
    "packages",
    "package cache",
    "microsoft\\windowsapps",
    "appdata\\local\\packages",
];

pub const DOCS_TERMS: &[&str] = &[
    "documentation",
    "help",
    "readme",
    "manual",
    "license",
    "changelog",
    "credits",
    "legal",
    "faq",
];

pub const ACCENT_COLORS: &[([u8; 3], [u8; 3])] = &[
    ([195, 177, 225], [150, 111, 214]), // Purple
    ([157, 78, 221], [123, 44, 191]),   // Deep Purple
    ([123, 154, 237], [91, 127, 219]),  // Blue
    ([144, 224, 239], [0, 150, 199]),   // Cyan
    ([144, 238, 144], [34, 139, 34]),   // Green
    ([255, 182, 193], [255, 105, 180]), // Pink
    ([255, 107, 107], [220, 47, 47]),   // Red
    ([255, 218, 185], [255, 140, 0]),   // Orange
];